name: CI/CD

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: echo "Dependency installed"
      
      - name: Test
        run: echo "Test succeed"

      - name: Build
        run : echo "Build successfully"

      - name: Deploy
        run: echo "https://htmlpreview.github.io/?https://github.com/sia-devops/sia-website/blob/main/src/index.html"